README.md
_config.yml
_includes/header.html
_includes/menu.html
index.md
location.md

In `da71c2a` I removed the `base` tag and made the links relative so that the site would work locally, but that only works locally because the site is at the root of the domain. On the server, this site sits in a sub-directory (e.g. `spa2018`) so these links, relative to the root, do not work on the server.
This commit fixes that by setting a `baseurl` (currently `/tmp/` but once the site is active that will be the actual directory we want to deploy to), and using Jekyll's `relative_url` filter to make URLs do the right thing.
Documentation here: https://jekyllrb.com/docs/templates/
Useful blog post (though it trails off in the middle of a thought...), here: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/.

Use `relative_url` to fix relative URLs

---

_includes/lead-a-session-nav.html
_includes/previous-conferences-nav.html
_layouts/page.html
formats.md
lead-a-session.md
organisers.md
previous-conferences.md
submission-stages.md
terms-and-conditions.md
themes.md

This PR adds the lead a session page and supplementary pages, and also fixes up the internal page navigations (these occur in the lead a session page and the previous conferences page).

Add lead a session page & supplementary pages

---

README.md

@jennyd pointed out that this was incorrect. This commit also includes the full path, and adds clarification around the PR/merge process.

Correct location of commands to run locally

---

README.md

This PR adds explicit instructions for running the site locally, as the previous instructions assumed some knowledge of jekyll.
It also adds instructions on how to change the internal navigation of the lead a session pages, which have their own menu.
@jennyd, as you will be making these changes and raised the original point that the instructions weren't clear, please could you review this and see if it makes sense to you, and if so, merge?
cc @eoinwoods @NTCoding as you are also collaborators and may wish to comment.

Update instructions for running the site locally

---

README.md
_config.yml
_includes/footer.html
_includes/header.html
bofs.md
index.md
interactivity.md
lead-a-session.md
location.md
refunds-and-cancellations.md
sponsor.md
sponsors.md
submission-stages.md
terms-and-conditions.md

As agreed with @annashipman, update all website content to use the new conference name: SPA Software in Practice.

Use new conference name everywhere

---

README.md
scripts/deploy.sh

The deployment does not purge on deploy, which means that existing pages that are no longer present in the source are not removed. This is good because we should not be removing pages that have been published as that breaks existing links, and it is necessary because the programme is generated from the scripts part of the site and is deployed in a different way; if this purged on deploy it would delete the programme every time.

Add clarification about deployment

---

_includes/header.html
index.md
spa.css

On narrow devices (notably, iPhones 5/5S/SE) the new conference name, in a 48px face, is just wide enough that it induces horizontal scrolling. To counter that, let's just reduce the font size back to the default. This isn't a perfect fix but, given the current layout, it's probably the best compromise.
It turns out that the location image on the homepage is *also* wide enough to cause this issue, so I've fixed that.
This PR also puts the header image on all pages and the date on all pages as now homepage header is smaller, it looks odd removing the image from page to page.

Ensure the new conference name isn't too wide

---

README.md
_config.yml
_includes/menu.html
sponsor.md

The current menubar is easy to understand, but isn't easy to make show the currently active page. It also requires some duplication, making future markup changes more complicated.
This change moves the control of the navigation structure into the `_config.yml` (though it could possibly be done another way), and then uses that structure to generate the menu programmatically. Menu items are rendered in the order they're stored in the array, and may either be the ID of a page, or a dictionary (expected to contain both `title` and `url`, which we output without touching).
The rendering code checks if the menu item is either the current page, or is mentioned in the current page's `has-nav` attribute and, if true, marks the menu item as selected.

Programmatically generate the menubar from config

---

_config.yml
_includes/menu.html

Since the programme is not generated from this Jekyll site, adding it to the navigation is a little complicated, so I have added this commented out in the config file.
I've also removed the comments from the menu include because to me, they actually made it harder to parse than without them.

Add programme to the navigation

---

previous-conferences.md

Firstly, this year's claim (23rd year) doesn't match up with last year's claim (21st year), and I also think neither are correct and the conference has actuallybeen running longer than that. In any case, to avoid having to update this page every year with a possibly incorrect year, let's just say "over 20 years" and update it in 5 or 10 years :)

Make age of conference a little more vague

---

_includes/header.html
programme_includes/footer.html
programme_includes/header.html
spa.css

The programme is generated using the PHP scripts and is published by the chairs via the PHP on the main site. However, it needs to look like the rest of the site and reflect any updates to header and footer, so this PR adds a header and footer that will be included with the programme.
I've also made some changes to the design of the programme so that if there are 4 tracks rather than 3 it looks right, and to have it include the actual room names so it is a useful tool during the conference itself. This PR includes changes to the CSS required to support that.

Support new programme rendering

---

README.md

This commit changes the heading from a h2 to a h1, as it should be; without that it's rather lost in what looks like a list of detail on how to run the site locally.

Minor change to clarify how to publish the site

---

_posts/2018-02-28-launching-spa-2018.md

Fix a couple of typos and the conference dates in the launch blog post.

Blog post typos and dates

---

submission-stages.md

We want to be able to link directly to the programme meeting section in an
email.

Add ids to headings on submission stages page

---

info-for-speakers.md
terms-and-conditions.md

Add `id`s to speaker info page headings so that we can link to specific sections in emails.

Ids for speaker info page

---

_config.yml
lead-a-session.md

This removes the 'Lead a session' from the main navigation menu, but leaves the page in situ so it can still be referred to.
It also adds a comment to the page to indicate that submissions are closed, in case anyone finds their way to the page.

Submissions are closed so remove it from main menu

---

_includes/footer.html
_includes/header.html
terms-and-conditions.md

This PR updates the T&Cs for the site to clarify how we use users' data. Comments are very welcome, particularly on whether we need [c598b9d](https://github.com/spaconference/spa-website/commit/c598b9d) or whether that is too much information.

Update Terms and Conditions

---

_includes/header.html
_layouts/programme_page.html
programme_includes/person_header.html
programme_includes/session_header.html

It turns out that the CSS of the session and user pages needs to be differentiated. In previous years this hasn't been a problem because we didn't include the main programme header in the page (e.g. https://spaconference.org/spa2017/sessions/session715.html).
We've now realised that the session and user pages should have the same header as the programme. Like the programme, these pages are generated from inside the PHP scripts so will need to grab the include from the jekyll site (to ensure it's always up to date with the rest of the site).
However, we can't use the same include as the programme because the user page needs a body class of 'person' to display correctly, and the session page requires no body class (rather than 'programme').
The way to make this easiest to understand is to …

Create new headers for different programme pages

---

README.md

One of the issues that caused #56 is swapping out the baseurl wherever it appears in the URL rather than only at the beginning. This PR updates the documentation to show how the tests can be correctly run, and adds some examples.

Change documentation so tests run locally

---

README.md

This is no longer used to build the SPA website.

Deprecate repo
