spaconference/spa-website

- organisers.md
This commit removes two stray closing table tags.
The whole page needs fixing, but can do that later; for now this is just to test that everything works as it should after moving the repo to the spaconference org from my own org.
> Fix more stray tags

- lead-a-session.md
A few minor edits.
We still need to finalise the submission dates - I'll make a separate PR for that.
> Update CFP wording

- index.md
- submission-stages.md
See individual commits for details.
> Small content fixes

- index.md
- lead-a-session.md
- refunds-and-cancellations.md
See individual commits for details.
> More small fixes

- _config.yml
- book-now.md
- lead-a-session.md
- refunds-and-cancellations.md
- submission-stages.md
Update all the dates on the site for the 2018 conference and move them into variables to make them easier to change in future.
> Update all dates for the 2018 conference

- _config.yml
The programme meeting will be on 9th March, and the deadline for reviewing is a couple of days before that.
Also update the `current_year` to 2018 🎉 📆
> Update some dates

- README.md
Please ignore this, I am testing something to do with the Travis deploy.
> Blank line to test the Travis deploy

- _includes/lead-a-session-nav.html
- info-for-speakers.md
I'm pretty sure that we used to have `<ul>` styled as bullet points, but that
doesn't seem to be working now.
> Add a page with info for accepted speakers

- _config.yml
- bofs.md
- social.html
The programme will link to these pages from the birds of a feather and dinner & diversions slots, so they need to exist before we publish the programme.
> Add pages needed for programme

- sponsors.md
Corrected my previous cack-handed update to master to correct the image reference.  I don't think the Contino entry is correct but didn't change that.
> Added Endava to sponsors.md

- social.html
Can someone please check it and merge it? For some reason, the tests don't run in my mac, and I have no idea why. It happened also when I added Zuhlke to the sponsors page. I've just added some content to existing pages with no other changes.
> Added information about diversions

- social.html
I realised I made a copy and paste mistake with the wording.
> Fixed wording.

- index.md
> Change the Nth year!

- README.md
Linking to instructions in SPA handbook.
> Add note about change of year

- location.md
This [tweet](https://twitter.com/davidnoob/status/1082727767160938496) made me realise we really should have this information.
> Add accessibility info

- Gemfile.lock
> Update Nokogiri to deal with security vuln

- README.md
- docker-compose.yml
- Add docker-compose with the jekyll base image
- add instructions to readme
> Add Docker compose to run the site locally with Docker

- _config.yml
We are sending out the email in 5 minutes and need to update the close date for CfP to 23:59 on Sunday 24th Feb. This does that.
> updating the CfP close date to 24th Feb

- _config.yml
- _includes/header.html
- lead-a-session.md
removed button from header, changed text on Lead a Session page and fixed up _config.yml
> removing submit session button

- sponsor.md
I have added a bit more of a sales pitch on why sponsor us. 
I have added pricing and I have added discounted tickets with each of the packages.
Given we are giving discounted tickets we should look to get the tickets stuff up soon as well.
Outstanding is the accessibility and diversity sponsorship should also be decided now if we can.
Diversity would be to take our 15 £99 diversity tickets to £0 each.
Accessibility has not really been decided but I think we were considering captioning but we are uncertain and would need a price. Thoughts?
> adding pricing and discounted tickets to sponsor page

- sponsor.md
Changed the number of corporate tickets for lunch to match the ones for dinner.
> Updating sponsorship with pricing

- book-now.md
Added booking information for diversity tickets to booking page, as well as an additional button to link to the diversity form.
> Changed text of book now buttons

- _config.yml
- sponsors.md
Remove sponsor us link.
Add link to Contino.
> Sponsors page 2019

- bof.md
simply changing the name should fix this issue. No change to the text from last year.
> changing the file name from bofs.md to bof.md

- _config.yml
missed this in my enthusiasm to get the page up
> getting the config.yml to compile the new bof page

- social.html
fixing the dates to reflect this years conf not last years
> updating dates on social

- social.html
> just a trivial change to social.html

- social.md
don't know why it has the old naming style
> renaming social.html to .md
